name: "Build Playground App"

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build App
        runs-on: ubuntu-latest
        steps:
            - name: Cache Flutter dependencies
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.pub-cache
                  key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}

            - name: Check Out Code and
              uses: actions/checkout@v4

            - name: Get flutter action
              uses: subosito/flutter-action@v2
              with:
                  channel: "stable"

            - name: Run Pub Get
              run: flutter pub get
            # Removed test
            # - run: flutter test
            - name: Run Flutter build
              run: flutter build apk --release --split-per-abi

            - name: Release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: "build/app/outputs/flutter-apk/*.apk"
                  name: Flutter Playground
                  tag: v1.0.${{ github.run_number }}
                  token: ${{ secrets.GITHUB_TOKEN }}
